# Generated by Django 2.2.7 on 2019-12-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='img/catalog'),
        ),
        migrations.AlterField(
            model_name='category',
            name='translit_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
