# Generated by Django 2.2.7 on 2019-12-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_profile_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
