# Generated by Django 2.2.7 on 2019-12-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='img/avatar/default.png', null=True, upload_to='img/avatar'),
        ),
    ]
