# Generated by Django 2.2.7 on 2019-12-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price']},
        ),
    ]
