# Generated by Django 2.2.7 on 2019-12-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='released',
            field=models.BooleanField(default=False),
        ),
    ]
